version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Hikabase
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql

  app:
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    build:
      context: .
      dockerfile: Dockerfile
      #image: blog-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql 
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: Hikabase
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - .:/app  
