version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_app_development
    volumes:
    - ./db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
      #image: blog-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db  
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_NAME: blog_app_development
    volumes:
      - .:/app  
