version: '3.8'

services:
  db:
  image: mysql:latest
  restart: always
  environment:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: root
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  volumes:
  - ./db_data:/var/lib/mysql

app:
  build:
    context: .
    dockerfile: Dockerfile
    image: blog-app
    restart: always
    ports:
    - 3000:3000
    depends_on:
    - db
    volumes:
    - .:/Hikasami
